// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsbaxkyflpypffnjsjrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzYmF4a3lmbHB5cGZmbmpzanJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODAzNDIsImV4cCI6MjA3NDY1NjM0Mn0.oVT3MsUkrvUTpQAlBHOZ5u4vP0GOHt_BNjoTCx3wwDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});